# Generated by Selenium IDE
from selenium.webdriver.common.by import By
from core.selenium.common import initialize_driver


def test_testProfile():
    driver = initialize_driver()
    driver.get("http://localhost:5000/")
    driver.set_window_size(1854, 1048)
    driver.find_element(By.LINK_TEXT, "Sample dataset 4").click()
    driver.find_element(By.LINK_TEXT, "Doe, Jane").click()


# Call the test function
test_testProfile()
