"""Added active column

Revision ID: 409208c1be49
Revises: 47b26adae59f
Create Date: 2024-12-13 19:26:52.889281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409208c1be49'
down_revision = '47b26adae59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
